### ISSUE TITLE
Wear OS Tiles and Media Service

### ISSUE THREAD

**Issue by vdwapps** [android/wear-os-samples#227]
Hello,
The Wear OS tiles example is great, not so much of an issue but how would one start the background media service that play the songs selected in the primary app, when every I try to start the service , I get the following error. The is no UI thread to reference and the documentation only has to methods for onclick, LoadAction and LaunchAction. 

override fun onTileRequest(request: TileRequest) = serviceScope.future {
        when(request.state!!.lastClickableId){
            "play"-> playClicked()
        }....

suspend fun playClicked(){

       
        try {
            // Convert the asynchronous callback to a suspending coroutine
            suspendCancellableCoroutine<Unit> { cont ->
                mMediaBrowserCompat = MediaBrowserCompat(
                    applicationContext, ComponentName(applicationContext, MusicService::class.java),
                    mMediaBrowserCompatConnectionCallback, null
                )
                mMediaBrowserCompat!!.connect()

            }
        }catch (e:Exception){
            e.printStackTrace()
        } finally {
          mMediaBrowserCompat!!.disconnect()
        }
    }

ERROR
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()

**Comment by yschimke** [comment]
I answered on https://stackoverflow.com/questions/71315600/wear-os-tiles-and-media-service

> serviceScope is running on Dispatchers.IO, you should use withContext(Dispatchers.Main) when making any calls to MediaBrowserCompat.

**Comment by vdwapps** [comment]
Thank you appreciate the feedback, here is the exact error

W/System.err: java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-2,5,main] that has not called Looper.prepare()
2022-03-02 10:45:29.826 3903-3927/com.vdwapps.music W/System.err:     at android.os.Handler.<init>(Handler.java:205)
2022-03-02 10:45:29.826 3903-3927/com.vdwapps.music W/System.err:     at android.os.Handler.<init>(Handler.java:118)
2022-03-02 10:45:29.826 3903-3927/com.vdwapps.music W/System.err:     at android.support.v4.media.MediaBrowserCompat$CallbackHandler.<init>(MediaBrowserCompat.java:2124)
2022-03-02 10:45:29.826 3903-3927/com.vdwapps.music W/System.err:     at android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi21.<init>(MediaBrowserCompat.java:1653)
2022-03-02 10:45:29.826 3903-3927/com.vdwapps.music W/System.err:     at android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi23.<init>(MediaBrowserCompat.java:2025)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at android.support.v4.media.MediaBrowserCompat$MediaBrowserImplApi26.<init>(MediaBrowserCompat.java:2042)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at android.support.v4.media.MediaBrowserCompat.<init>(MediaBrowserCompat.java:208)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at com.vdwapps.muzica.tiles.PlayNextSongTileService.playClicked(PlayNextSongTileService.kt:305)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at com.vdwapps.muzica.tiles.PlayNextSongTileService$onTileRequest$1.invokeSuspend(PlayNextSongTileService.kt:99)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
2022-03-02 10:45:29.827 3903-3927/com.vdwapps.music W/System.err:     at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)

**Comment by vdwapps** [comment]
Thanks Yuri, that worked. Here is how the function looks for anyone trying to implement this

suspend fun playClicked() = withContext(Dispatchers.Main){


        try {
            // Convert the asynchronous callback to a suspending coroutine
            suspendCancellableCoroutine<Unit> { cont ->
                mMediaBrowserCompat = MediaBrowserCompat(
                    applicationContext, ComponentName(applicationContext, MusicaPlayerService::class.java),
                    mMediaBrowserCompatConnectionCallback, null
                )
                mMediaBrowserCompat!!.connect()

            }
        }catch (e:Exception){
            e.printStackTrace()
        } finally {
          mMediaBrowserCompat!!.disconnect()
        }
    }```

**Comment by vdwapps** [comment]
The above worked, but was suspending the program, the below one is working well

fun playClicked(){
mainHandler.post(playSong)
}

  private val playSong: Runnable = object : Runnable {
        @RequiresApi(Build.VERSION_CODES.N)
        override fun run() {
            mMediaBrowserCompat = MediaBrowserCompat(
                applicationContext, ComponentName(applicationContext, MusicaWearService::class.java),
                mMediaBrowserCompatConnectionCallback, null
            )
            mMediaBrowserCompat!!.connect()
        }
    }```

**Comment by yschimke** [comment]
What do you mean suspending the program? I'll take a look, something going wrong if you have to use a runnable and post to a handler.  Where is it blocking?

**Comment by vdwapps** [comment]
The runnable method does not block the UI, but using the suspendCoroutine does suspend the function as its suppose to, the runnable does the job.

**Comment by yschimke** [comment]
Let's continue on StackOverflow.
