### ISSUE TITLE
Issue while building wear apps [AlwaysOn]

### ISSUE THREAD

**Issue by ahsan95050** [android/wear-os-samples#75]
I am trying to explore Wear apps after loading the Always app I get the following error

=========================
Error:No such property: GradleVersion for class: JetGradlePlugin

Consult IDE log for more details (Help | Show Log)
==========================

IDE Log errors
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
2021-02-16 14:58:26,359 [se-915-b01]  ERROR - ctionCallback.TimedOutCallback - Android Studio 3.0.1  Build #AI-171.4443003 
2021-02-16 14:58:26,359 [se-915-b01]  ERROR - ctionCallback.TimedOutCallback - JDK: 1.8.0_152-release 
2021-02-16 14:58:26,359 [se-915-b01]  ERROR - ctionCallback.TimedOutCallback - VM: OpenJDK Server VM 
2021-02-16 14:58:26,359 [se-915-b01]  ERROR - ctionCallback.TimedOutCallback - Vendor: JetBrains s.r.o 
2021-02-16 14:58:26,359 [se-915-b01]  ERROR - ctionCallback.TimedOutCallback - OS: Windows 7 
2021-02-16 16:30:41,749 [se-915-b01]   INFO - build.invoker.GradleTaskFinder - Unable to find Gradle tasks for project 'AlwaysOn' using BuildMode REBUILD 
2021-02-16 16:30:41,754 [se-915-b01]   INFO - ild.invoker.GradleBuildInvoker - About to execute Gradle tasks: [] 
2021-02-16 16:31:18,856 [se-915-b01]   INFO - ide.actions.ShowFilePathAction - 
Exit code 1 
--------------------------------------
Gradle version from the Project Structure is 6.5

Please let me know if you need more information/details or  I am missing some plugin to build this app

[idea.log](https://github.com/android/wear-os-samples/files/5992523/idea.log)
[threadDump-20210216-145152.txt](https://github.com/android/wear-os-samples/files/5992526/threadDump-20210216-145152.txt)

**Comment by alexvanyo** [comment]
Hi @ahsan95050 , the `AlwaysOn` sample was recently updated. If you're still running into this issue or a different one with the latest version of Android Studio please re-open or create a new issue.
