### ISSUE TITLE
Auth Device  Grant FileNotFoundException

### ISSUE THREAD

**Issue by kotya341** [android/wear-os-samples#967]
Hello folks,
Could you please help me with the DAG flow? 
Just playing with a sample app. 
I am using Pixel 5 paired with Pixel Watches 2.

set clients and secrets and when I click authorize I face an exception
```
java.io.FileNotFoundException: https://oauth2.googleapis.com/device/code
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:255)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at com.example.android.wearable.oauth.util.RequestsKt$doPostRequest$2.invokeSuspend(Requests.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
I see an authorization fails error message on the screen.
![image](https://github.com/android/wear-os-samples/assets/2707599/25c5ca45-3e6f-46ba-8bf1-77520c255937)

**Comment by kotya341** [comment]
sorry problem was that I tried to reuse client that I set up for PKCE and we need different type for DAG flow
