### ISSUE TITLE
AlwaysOnTests invalid intent code

### ISSUE THREAD

**Issue by yschimke** [android/wear-os-samples#990]
From https://github.com/android/wear-os-samples/actions/runs/7553630443?pr=989

```
java.lang.IllegalArgumentException: com.example.android.wearable.wear.alwayson: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:401)
	at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:671)
	at android.app.PendingIntent.getBroadcast(PendingIntent.java:658)
	at com.example.android.wearable.wear.alwayson.AlwaysOnAppTests$textIsCorrectAfterGoingIntoAmbientModeAndReceivingIntent$1.invokeSuspend$lambda$1(AlwaysOnAppTests.kt:186)
	at com.example.android.wearable.wear.alwayson.AlwaysOnAppTests$textIsCorrectAfterGoingIntoAmbientModeAndReceivingIntent$1.$r8$lambda$a8G_TkkhNUXdHJxiI15hx-rBA5Y(Unknown Source:0)
	at com.example.android.wearable.wear.alwayson.AlwaysOnAppTests$textIsCorrectAfterGoingIntoAmbientModeAndReceivingIntent$1$$ExternalSyntheticLambda0.perform(D8$$SyntheticClass:0)
```

**Comment by kul3r4** [comment]
Closing this as AlwaysOn has been deprecated.
